name: carbon
description: IBM Carbon Design System for Flutter
version: 0.0.1
homepage: https://github.com/NourEldinShobier/carbon-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  stylex: ^1.1.0
  pmvvm: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: IBMPlexSans-Light
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSans-SemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
