name: lab
description: Carbon lab

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0
  flutter_svg: ^0.21.0-nullsafety.0
  pmvvm: ^2.0.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: IBMPlexSans-Light
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSans-SemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
